### ISSUE TITLE
Uploading sample portfolio results in `"POST /portfolio-upload:complete failed"`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/app#214]
Repro steps: 
- log in to the WebApp at https://pacta.dev.rmi.siliconally.dev/
- navigate to https://pacta.dev.rmi.siliconally.dev/en/upload, and download-then-upload the sample portfolio provided

I have double checked this time, and the downloaded file _is_ in fact a `.csv` (indicating this is likely distinct from #209 )

@bcspragu we chatted about this briefly, but wanted to get the details documented for posterity. 

Error details:
``` json
{
  "name": "Error",
  "message": "POST /portfolio-upload:complete failed",
  "stack": [
    "Error",
    "    at x$ (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:2228:19065)",
    "    at bf.fn (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:2228:26982)",
    "    at bf.run (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:1:4716)",
    "    at get value (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:1:13176)",
    "    at We (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:1:12085)",
    "    at https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:2229:244",
    "    at r (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:1:16225)",
    "    at G (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:1:31661)",
    "    at https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:2228:26459",
    "    at r (https://pacta.dev.rmi.siliconally.dev/_nuxt/entry.3910a747.js:1:16225)"
  ]
}
```

**Comment by bcspragu** [comment]
Not sure which issue this was (could have been CORS or something else), but the flow should work on the dev site (hosted in the RMI tenant) now. Please re-open if this is still an issue you're seeing!
